# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb43f1b6a122b7019697073b704bf8e942926dbb149c8dde45e3c33cba698aff2bc3cae49bc46fc15b4bbbffbf413fde14bf06d1474b34fa90bcd35121c65c2

test:
  secret_key_base: ccc7efa3b62c92cb60c18d344830e9e9726e00ee06cd2ccc7e39423307c4bf765e486bfacf2f0a1152345b6ba3176562057e005c2898b45cd9a16cfd1d811d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
